name: Real EA Backtest

on:
  push:
    paths:
      - '**.mq4'
  workflow_dispatch:

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Pull MT4 Docker
      run: docker pull ghcr.io/ea-broker/metatrader-test:latest

    - name: Run EA Backtest
      run: |
        docker run --rm -v ${{ github.workspace }}:/data \
          ghcr.io/ea-broker/metatrader-test:latest \
          backtest \
          --symbol XAUUSD \
          --timeframe M5 \
          --ea /data/AYA_AntiSideway_v1.mq4 \
          --from 2024-01-01 \
          --to 2024-01-31 \
          --deposit 10000 \
          --report /data/backtest-result.html

    - name: Upload backtest result
      uses: actions/upload-artifact@v3
      with:
        name: EA Backtest Report
        path: backtest-result.html
